# Generated by Django 3.2.20 on 2023-08-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendtalk', '0007_auto_20230829_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
