# Generated by Django 3.2.20 on 2023-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendtalk', '0014_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='path/to/default-profile-image.png', null=True, upload_to='avatars/'),
        ),
    ]
