# Generated by Django 3.2.20 on 2023-09-07 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendtalk', '0015_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='default_profile_image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
